<?php

use Flm\Media\Screenshots;
use Flm\ShellCmds;

if (!defined('STDOUT'))
{
    exit;
}

include 'boot.php';

class  FileManagerMediaTests {
    /** black-320x240-30s-1fps.mp4 in base64
     * ffmpeg -f lavfi -i color=black:s=320x240:r=1 -c:v libx264 -preset veryslow -vf format=yuv420p -an -t 30 test-black-30s-1fps.mp4
     * @var string
     */
    const VIDEO_FILE = 'AAAAIGZ0eXBpc29tAAACAGlzb21pc28yYXZjMW1wNDEAAAAIZnJlZQAAA+ptZGF0AAACrwYF//+r3EXpvebZSLeWLNgg2SPu73gyNjQgLSBjb3JlIDE2MCByMzAxMSBjZGU5YTkzIC0gSC4yNjQvTVBFRy00IEFWQyBjb2RlYyAtIENvcHlsZWZ0IDIwMDMtMjAyMCAtIGh0dHA6Ly93d3cudmlkZW9sYW4ub3JnL3gyNjQuaHRtbCAtIG9wdGlvbnM6IGNhYmFjPTEgcmVmPTE2IGRlYmxvY2s9MTowOjAgYW5hbHlzZT0weDM6MHgxMzMgbWU9dW1oIHN1Ym1lPTEwIHBzeT0xIHBzeV9yZD0xLjAwOjAuMDAgbWl4ZWRfcmVmPTEgbWVfcmFuZ2U9MjQgY2hyb21hX21lPTEgdHJlbGxpcz0yIDh4OGRjdD0xIGNxbT0wIGRlYWR6b25lPTIxLDExIGZhc3RfcHNraXA9MSBjaHJvbWFfcXBfb2Zmc2V0PS0yIHRocmVhZHM9NyBsb29rYWhlYWRfdGhyZWFkcz0xIHNsaWNlZF90aHJlYWRzPTAgbnI9MCBkZWNpbWF0ZT0xIGludGVybGFjZWQ9MCBibHVyYXlfY29tcGF0PTAgY29uc3RyYWluZWRfaW50cmE9MCBiZnJhbWVzPTggYl9weXJhbWlkPTIgYl9hZGFwdD0yIGJfYmlhcz0wIGRpcmVjdD0zIHdlaWdodGI9MSBvcGVuX2dvcD0wIHdlaWdodHA9MiBrZXlpbnQ9MjUwIGtleWludF9taW49MSBzY2VuZWN1dD00MCBpbnRyYV9yZWZyZXNoPTAgcmNfbG9va2FoZWFkPTYwIHJjPWNyZiBtYnRyZWU9MSBjcmY9MjMuMCBxY29tcD0wLjYwIHFwbWluPTAgcXBtYXg9NjkgcXBzdGVwPTQgaXBfcmF0aW89MS40MCBhcT0xOjEuMDAAgAAAAD9liIEAAv/+99S3zLLuByK2C6j3op4mX0N1JQGblsTtOoAAuvV/t9tvzdEFpNBAAAADAgIPWNn21zc04jI9OoEAAAAOQZoJLYgv//7aplgAAdUAAAANQZ4QhxBf/wAAAwBUwQAAAAwBnhgmiCv/AAADAUEAAAAMAZ4YRogr/wAAAwFBAAAADAGeGGaIK/8AAAMBQQAAAAwBnhitSCv/AAADAUEAAAAMAZ4YzUgr/wAAAwFBAAAADAGeGO1IK/8AAAMBQQAAAAwBnhkNSCv/AAADAUEAAAAUQZoZyTUCAtEymBBX//7WpVAAAdUAAAANQZ4hZcQW/wAAAwDPgAAAAAwBnilFogr/AAADAUEAAAAMAZ4pjJIK/wAAAwFBAAAADAGeKaySCv8AAAMBQQAAA6xtb292AAAAbG12aGQAAAAAAAAAAAAAAAAAAAPoAAA6mAABAAABAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAC1nRyYWsAAABcdGtoZAAAAAMAAAAAAAAAAAAAAAEAAAAAAAA6mAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAAAAABQAAAAPAAAAAAACRlZHRzAAAAHGVsc3QAAAAAAAAAAQAAOpgAAIAAAAEAAAAAAk5tZGlhAAAAIG1kaGQAAAAAAAAAAAAAAAAAAEAAAAPAAFXEAAAAAAAtaGRscgAAAAAAAAAAdmlkZQAAAAAAAAAAAAAAAFZpZGVvSGFuZGxlcgAAAAH5bWluZgAAABR2bWhkAAAAAQAAAAAAAAAAAAAAJGRpbmYAAAAcZHJlZgAAAAAAAAABAAAADHVybCAAAAABAAABuXN0YmwAAACtc3RzZAAAAAAAAAABAAAAnWF2YzEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAABQADwAEgAAABIAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY//8AAAA3YXZjQwFkABb/4QAaZ2QAFqxyBEFB+wEQAAADABAAAAMAIPFi2EYBAAZo6EOPLIv9+PgAAAAAEHBhc3AAAAABAAAAAQAAABhzdHRzAAAAAAAAAAEAAAAPAABAAAAAABRzdHNzAAAAAAAAAAEAAAABAAAAWGN0dHMAAAAAAAAACQAAAAEAAIAAAAAAAQACgAAAAAABAAEAAAAAAAMAAAAAAAAABAAAQAAAAAABAAGAAAAAAAEAAIAAAAAAAQAAAAAAAAACAABAAAAAABxzdHNjAAAAAAAAAAEAAAABAAAADwAAAAEAAABQc3RzegAAAAAAAAAAAAAADwAAAvYAAAASAAAAEQAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAYAAAAEQAAABAAAAAQAAAAEAAAABRzdGNvAAAAAAAAAAEAAAAwAAAAYnVkdGEAAABabWV0YQAAAAAAAAAhaGRscgAAAAAAAAAAbWRpcmFwcGwAAAAAAAAAAAAAAAAtaWxzdAAAACWpdG9vAAAAHWRhdGEAAAABAAAAAExhdmY1OC40NS4xMDA=';

    private $tempTestDir;
    /**
     * @var bool|string
     */
    private $videoFile;
    private string $imageFile;

    public function testScreenshots() {
        $screens = new Screenshots($this->videoFile, $this->imageFile,
            ['rows' => 3, 'columns' => 1, 'width' => 130]
        );
        var_dump(__METHOD__,
            $screens->getSheetCmd()->cmd(),
            $screens->getSheetCmd()->run()
        );

    }

    public function runTests() {
        $this->tempTestDir = '/tmp/'.static::class;

        // cleanup
        ShellCmds::recursiveRemove($this->tempTestDir)->run();
        ShellCmds::mkdir($this->tempTestDir, true, '0777')->run();

        $this->videoFile = tempnam($this->tempTestDir, "video").'.mp4';
        $this->imageFile = $this->videoFile.'.jpeg';

        file_put_contents($this->videoFile, base64_decode(self::VIDEO_FILE));

        $this->testScreenshots();
    }
}

(new FileManagerMediaTests())->runTests();





